language: php

sudo: required
dist: precise

install: true
script:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb
  - sudo service elasticsearch restart

