language: android
  
matrix:
  include:
    - sudo: false
      dist: precise
    - sudo: false
      dist: precise
    - sudo: false
      dist: trusty
    - sudo: required
      dist: trusty

install: true
script: python -V
