# Trigger build
language: csharp

matrix:
  include:
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
      
addons:
  apt:
    packages:
      - tree

install: true
script: true
