language: node_js

sudo: false

matrix:
  include:
    - os: "linux"
      env: NODE_VERSION="5.6"
    - os: "linux"
      env: NODE_VERSION="4.2"
    - os: "linux"
      env: NODE_VERSION="0.12"

install: true
script: true
