sudo: false
dist: trusty

language: node_js
node_js: stable

install: true
script: true

deploy:
  provider: anynines
  edge:
    branch: dj-add-skip-deploy-option
  username: johndoe@example.com
  password: secretpassword
  organization: myorganization
  space: staging
  skip_deploy: true
