sudo: required
sudo: trusty

matrix:
  include:
    # General checks
    - os: linux
      go: 1.7.1
      env: TARGETS="check"

    # Filebeat
    - os: linux
      go: 1.7.1
      env: TARGETS="-C filebeat testsuite"
      
install: true
script: true
