language: ruby

install: true

script:
  - date > ./date.txt
  - git -c "user.name=$NAME" -c "user.email=$EMAIL" add date.txt
  - git -c "user.name=$NAME" -c "user.email=$EMAIL" commit -m "Updated date.txt"
  - git remote -v 
  - git remote remove origin 
  - git remote add origin git@github.com:cotsog/travis_ci_prod_regular.git 
  - git -c "user.name=$NAME" -c "user.email=$EMAIL" push origin master
