language: rust
sudo: required
dist: trusty

services:
  - mysql
addons:
  postgresql: '9.4'

install: true
script:
  - pkg-config --variable=prefix mysqlclient     # installation prefix directory
  - pkg-config --variable=includedir mysqlclient # header file directory
  - pkg-config --variable=libdir mysqlclient     # library directory
