language: ruby

install: true

script: true

before_deploy:
  - echo "before_deploy!"

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "test"
  - provider: s3
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "S3 Bucket"
    skip_cleanup: true
