language: node_js
node_js: 5.6.0
install:
  - nvm --version
  - rm -rf /home/travis/.nvm
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - source /home/travis/.bashrc
  - nvm --version
script: true
  
