sudo: required
dist: trusty

language: c

matrix:
  include:
    - group: deprecated-2017Q2
    - group: stable

install: true
script:
  - which pip && pip --version
  - which pip3 && pip3 --version
  - which python3 && python3 -V
  - sudo which python3 && sudo python3 -V
  - sudo ln -svf $(which python3) /usr/bin/python3
  - which python3 && python3 -V
  - sudo which python3 && sudo python3 -V
  - which lsb_release
  - sudo cat $(which lsb_release)
  - lsb_release -a
  - pip3 install pytest meson
  - find /opt/python -name "lsb_release*"
  - pip check

