language: generic
addons:
  apt:
    packages:
      - python3-dev
matrix:
  include:
    - sudo: false
      dist: precise
    - sudo: required
      dist: precise
    - sudo: false
      dist: trusty
    - sudo: required
      dist: trusty
    
install: true
script: pip install awscli
