language: ruby

install: true

script:
  - date > ./date.txt
  - git -c "user.name=$NAME" -c "user.email=$EMAIL" add date.txt
  - git -c "user.name=$NAME" -c "user.email=$EMAIL" commit -m "Updated date.txt"
  - git -c "user.name=$NAME" -c "user.email=$EMAIL" push origin master
