language: ruby

matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
      rvm: 2.3.1

before_install:
  - gem install bundler
install: true

script:
  - bundle --version
