language: java
dist: precise
sudo: required

install:
  - curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/bin/jq
  - export PATH = PATH:~/bin
  - jq --version

script: true
