language: ruby
sudo: false
dist: trusty

branches:
  only:
    - master

addons:
  apt:
    packages:
      - hunspell

install: echo "install"

script:
  - echo badword | hunspell
  - echo somee words ar good some badd | hunspell
