language: c
matrix:
  include:
    - os: osx
      env: CACHE_NAME=osx
      os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 CACHE_NAME=linux
      compiler: clang

cache	
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

install:	
  - nvm install 6
  - npm install electron-builder@next
  - travis_wait npm install
  - npm prune
