language: node_js

matrix:
  include:
    - sudo: false
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

addons:
  firefox: "50.0b6"

install: true
script: firefox -v
