language: ruby

matrix:
  include:
    - sudo: false
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

install: true

script:
  - wget https://tools.protorz.net/clamav/main.cvd
  - wget https://jcenter.bintray.com/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812.jar
