language: erlang
  
matrix:
  include:
    - sudo: false
      dist: precise
      otp_release: 19.2
    - sudo: required
      dist: precise
      otp_release: 19.2
    - sudo: false
      dist: trusty
      otp_release: 19.2
    - sudo: required
      dist: trusty
      otp_release: 19.2

install: true
script:
  - erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
