language: java

matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
      jdk: oraclejdk9
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
      jdk: oraclejdk9
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
      jdk: oraclejdk9
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty
      jdk: oraclejdk9
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
      jdk: oraclejdk8
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
      jdk: oraclejdk8
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
      jdk: oraclejdk8
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty
      jdk: oraclejdk8
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
      jdk: oraclejdk7
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
      jdk: oraclejdk7
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
      jdk: oraclejdk7
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty
      jdk: oraclejdk7
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
      jdk: openjdk6
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
      jdk: openjdk6
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
      jdk: openjdk6
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty
      jdk: openjdk6

addons:
  apt:
    packages:
      - openjdk-8-jre

install: true
script: java -version
