sudo: required
dist: trusty

language: c

matrix:
  include:
    - dist: stable
    - dist: deprecated-2017Q2

install:
  - sudo apt-get install lsb-release
script:
  - sudo which python3
  - sudo python3 -V
  - sudo ln -svf $(which python3) /usr/bin/python3
  - sudo which python3
  - sudo python3 -V
  - sudo cat $(which lsb_release)
  - sudo python3 -m pip install pytest meson

