language: node_js
sudo: required
dist: trusty
install: true
script: true
jobs:
  include:
    - stage: precache
      script: true
    - stage: test
      node_js: 6.9.1
      script: echo test
    - stage: deploy
      script: echo deploy
