language: ruby

matrix:
  include:
    - sudo: false
      rvm: 2.3
    - sudo: required
      dist: precise
      rvm: 2.3
    - sudo: required
      dist: trusty
      rvm: 2.3

install: true
script:
  - ruby -v
