matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise

addons:
   apt:
      sources:
        - couchbase-precise
      packages:
        - libcouchbase-dev=2.7.3-1_amd64
install: true

script: true
