language: node_js
node_js:
      - "6"
os: osx

osx_image: xcode8.2

cache:
  directories:
  - node_modules
  - app/node_modules


install:
    - nvm install 6
    - npm install electron-builder@next
    - npm install
    - npm prune
