sudo: false

language: java
  
install: true
script:
  - |
     if [ ! -f ./cache/https:/idnow-ios-2.10.0.tar.gz ]; then
       mkdir cache
       pushd cache
       curl --retry 3 -O https://downloads.idnow.de/ios/idnow-ios-2.10.0.tar.gz
       popd 
     fi
