matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise

addons:
   apt:
      sources:
        - couchbase-precise
      packages:
        - libcouchbase-dev:amd64=2.7.3-1
install: true

script: true
