language: ruby

sudo: false

install: true
script: true

deploy:
  provider: gae
  edge:
    source: cotsog/dpl
    branch: dj-gae-debug
  provider: gae
  keyfile: europe-bloombees-130a7189973e.json
  project: europe-bloombees
  module: develop
  default: false
  version: 2
  config: app.yaml
