language: python
  
matrix:
  include:
    - sudo: false
      dist: precise
      python: 3.5
    - sudo: false
      dist: precise
      python: 3.6
    - sudo: required
      dist: precise
      python: 3.5
    - sudo: false
      dist: trusty
      python: 3.5
    - sudo: required
      dist: trusty
      python: 3.5

install: true
script: pytest --version
