language: ruby

matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty

before_install:
  - sudo apt-get update
install: true
script: true
