language: ruby

sudo: required
dist: trusty

before_install:
  - docker --version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker --version # for verification

install: true
script: true
