language: php

sudo: required
dist: precise

install: true
script:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.5/elasticsearch-2.3.5.deb
  - sudo dpkg -i --force-confnew elasticsearch-2.3.5.deb
  - sudo service elasticsearch restart

