language: ruby

matrix:
  include:
    - sudo: required
      dist: trusty
      env: sudo=required dist=trusty
    - sudo: required
      dist: precise
      env: sudo=required dist=precise

script: true
install: sudo apt-get update
