language: python

install: true
script:
  - export FOO="BAR"
  - |
    if [ $FOO == "BAR" ]; then
      echo $FOO
    else
      echo "BAZ"
    fi
  - export FOO="BAZ"
  - |
    if [ $FOO == "BAR" ]; then
      echo $FOO
    else
      echo "BAZ"
    fi
