language: ruby
rvm: 2.2.4

sudo: required
dist: precise

install: true
script:
  - which bundler
  - echo $PATH
  - rvm 2.2.4 do gem uninstall bundler
  - rvm 2.2.4 do gem uninstall -x -i /home/travis/.rvm/gems/ruby-2.2.4@global bundler
  - which bundler
