language: ruby

matrix:
  include:
    - sudo: false
      dist: precise
    - sudo: required
      dist: precise
    
addons:
  postgresql: 9.4

install:
  - psql -c 'create database primary_test;' -U postgres
script:
  - psql -U postgres -f test.sql
