language: php



matrix:
  include:
    - sudo: false
      php: 7.0
    - sudo: false
      dist: trusty
      group: beta
      php: 7.0
    - sudo: required
      dist: precise
      php: 7.0
    - sudo: required
      dist: trusty
      php: 7.0

install: true
script:
  - php -i | grep "ICU version"
