matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise

addons:
   apt:
      sources:
        - couchbase-precise
      packages:
        - libcouchbase-dev

install: true

script: apt-cache dump | grep couch
