matrix:
  include:
    - os: "linux"
      env: NODE_VERSION="5.6"
    - os: "linux"
      env: NODE_VERSION="4.2"
    - os: "linux"
      env: NODE_VERSION="0.12"

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - npm install -g npm@3.8.5

install: echo "install"

script: echo "script"
