language: node_js

node_js: 6.3.1

install: echo "install!"
script: echo "script!"

deploy:
  skip_cleanup: true
  provider: heroku
  strategy: api
  api_key: $HEROKU_API_KEY
  app:
    master: chava-lovelace
    stage: chava-lovelace-stage
    dev: chava-lovelace-dev
