language: erlang

otp_release: 19.2
  
matrix:
  include:
    - sudo: false
      dist: precise
    - sudo: required
      dist: precise
    - sudo: false
      dist: trusty
    - sudo: required
      dist: trusty

install: true
script:
  - erl -eval 'erlang:display(erlang:system_info(version)), halt().' -noshell
