language: ruby

matrix:
  include:
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty

services:
  - mysql
      
install: true
script:
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'"
