language: ruby

matrix:
  include:
    - sudo: false
      dist: precise
    - sudo: required
      dist: precise
    
addons:
  postgresql: 9.4

install:
  - psql -c 'create database primary_test;' -U postgres
  - psql -U postgres -f sql/primarydb-dev.sql
script:
  - psql --version
  - psql -U postgres -f test.sql
