language: android
sudo: required
dist: precise
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
  - extra-google-m2repository
  - extra-google-google_play_services
  - addon-google_apis-google-23
  - sys-img-armeabi-v7a-google_apis-23
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install ia32-libs-sdl
before_script:
  - android list target
  - echo no | android create avd --force -n test -t android-23 --abi google_apis/armeabi-v7a
  - android list avd
  - emulator -avd test -no-skin -no-audio &
  - adb wait-for-device
  - android-wait-for-emulator
  - sleep 30
  - adb shell input keyevent 82 &
install: true
script: true
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
