language: java

matrix:
  include:
    - sudo: false
      dist: trusty
    - sudo: false
      dist: precise
    - sudo: required
      dist: trusty
    - sudo: required
      dist: precise

install: true
script: ./path/to/non-existent/script.sh
