language: php

matrix:
  include:
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
      php: 7.0
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty
      php: 7.0

install: true
script:
  - sudo apt-get install -qq -y --force-yes dnsmasq
