language: node_js

matrix:
  include:
    - node_js: '4.1'
      sudo: false
      dist: precise
      env: dist=precise
    - node_js: '4.1'
      sudo: false
      dist: trusty
      env: dist=trusty

addons:
  postgresql: '9.5'
  
services:
  - postgresql

install: true
script: true
