language: ruby

services:
  - postgresql

matrix:
  include:
    - sudo: false
      dist: trusty
      addons:
        postgresql: "9.4"
    - sudo: false
      dist: precise
      addons:
        postgresql: "9.6"

script: true
install: true
