language: erlang

otp_release:
  - 19.2
  
matrix:
  include:
    - sudo: false
      dist: precise
    - sudo: required
      dist: precise
    - sudo: false
      dist: trusty
    - sudo: required
      dist: trusty

install: true
script:
  - erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
