sudo: required
language: php

matrix:
  include:
    - php: 7.0
    - php: 7.0
      dist: trusty
      
before_install:
  - php -i | grep "ICU version"
  - wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-3ubuntu0.4_amd64.deb
  - sudo dpkg -i libicu52_52.1-3ubuntu0.4_amd64.deb
  - php -i | grep "ICU version"

install: true
script: true
