language: node_js
node_js: 6.9.1
sudo: required
dist: trusty
install: true
jobs:
  include:
    - stage: precache
      script: true
    - stage: test
      script: echo test
    - stage: deploy
      script: echo deploy
