sudo: required
language: android
jdk: oraclejdk8

env:
  global:
    - GRADLE_OPTS="-Xmx512m"
    - ANDROID_TARGET="android-24"
    - ANDROID_ABI="google_apis/armeabi-v7a"
    - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-24
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    - sys-img-armeabi-v7a-google_apis-24

install:
  - echo no | android create avd --force -n TestAVD -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd TestAVD -no-skin -no-audio -no-window &
  - adb wait-for-device get-serialno
  
before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
script: true
