language: php

matrix:
  include:
    - sudo: false
      dist: precise
      php: 5.6
    - sudo: false
      dist: trusty
      php: 5.6
    - sudo: required
      dist: precise
      php: 5.6
    - sudo: required
      dist: trusty
      php: 5.6

install: true
script: php -i | grep "FreeType"
