language: ruby

sudo: required

matrix:
  include:
    - dist: precise
      env: dist=PRECISE
    - dist: trusty
      env: dist=TRUSTY
    
install: true

script:
  - sudo apt-get update
  - sudo apt-get install libgmp-dev libreadline-dev gcc-multilib g++-multilib texinfo libgmp-dev:i386
