language: ruby

matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
      
addon:
  apt:
    packages:
      - tree

install: true
script: true
