language: ruby

install: true
script:
  - jq
  - jq --version

matrix:
  include:
    - sudo: false
      dist: trusty
    - sudo: required
      dist: trusty
    - sudo: false
      dist: precise
    - sudo: required
      dist: precise

