language: java

matrix:
  include:
    - sudo: false
      dist: precise
    - sudo: false
      dist: trusty
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

install: true
script: echo $USER
