language: cpp

sudo: required

install: echo "install!"
script: echo "script!"
after_success: echo "after_success!"
after_script: echo "after_script!"

addons:
  artifacts: true

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "S3 Bucket"
