sudo: required
dist: trusty

language: c

matrix:
  include:
    - group: deprecated-2017Q2
    - group: stable

install: true
script:
  - pip --version
  - which python3 && python3 -V
  - sudo which python3 && sudo python3 -V
  - sudo ln -svf $(which python3) /usr/bin/python3
  - which python3 && python3 -V
  - sudo which python3 && sudo python3 -V
  - sudo cat $(which lsb_release)
  - sudo python3 -m pip install pytest==3.1.3 meson==0.41.2

