language: ruby

sudo: false

install: true
script:
  - CONTAINER_PATH=$(cat /proc/self/cgroup | grep memory | cut -d':' -f3)
  - echo $CONTAINER_PATH
  - CONTAINER_ID=$(echo $CONTAINER_PATH | cut -d'/' -f2)
  - echo $CONTAINER_ID
  - cat /proc/meminfo
  - cat /proc/cpuinfo

matrix:
  include:
    - dist: precise
    - dist: trusty
