language: ruby
addons:
  apt:
    packages:
      - python-dev

env:
  global:
    - PLATFORM=foo
    - TEST_FLOW=bar


matrix:
  include:
    - sudo: false
      dist: precise

install: true
script: true
