language: ruby

sudo: false

install: true
script: true

deploy:
  provider: gae
  edge:
    source: cotsog/dpl
    branch: dj-gae-debug
  keyfile: europe-bloombees-130a7189973e.json
  project: europe-bloombees
  version: 2
  config: app.yaml
  debug: true
