language: ruby

sudo: required
dist: precise

install: true

script:	
  - sudo apt-get update
  - sudo apt-get install libsqlite3-dev libmysqlclient-dev libcurl4-openssl-dev
  - sudo apt-get install libxslt-dev libxml2-dev libgeoip-dev imagemagick
  - sudo apt-get install openjdk-7-jre gpsbabel poppler-utils
  - sudo add-apt-repository ppa:limparissoft/opencv-ppa -y
  - sudo apt-get update -q
  - sudo apt-get install opencv
