language: rust
sudo: required
dist: trusty

addons:
  postgresql: '9.4'

before_install:
  - sudo add-apt-repository -y ppa:ondrej/mysql-5.7
  - sudo apt-get update -qq
  - sudo apt-get install mysql-server-5.7 mysql-client-5.7

install: true
script:
  - pkg-config --variable=prefix mysqlclient     # installation prefix directory
  - pkg-config --variable=includedir mysqlclient # header file directory
  - pkg-config --variable=libdir mysqlclient     # library directory
