language: java

matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty

install:
  - jq --version || true
  - mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/bin/jq
  - export PATH=$PATH:~/bin
  - jq --version

script: true
