language: node_js
install: true
script: true
before_deploy:
  - echo "before deploy"
  - echo "before deploy"
deploy:
  provider: script
  script: echo "deploy"
after_deploy:
  - echo "after deploy"
  - echo "after deploy"
