sudo: false
dist: precise

language: node_js
node_js: 6.11.0

env:
  global:
    - NPM_TOKEN=blablabla

install: true
script: true

deploy:
  provider: packagecloud
  repository: scratch
  username: tomduckering
  dist: el/7
  token:
    secure: REDACTED
