language: php

matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty

install: true
script:
  - time sudo rm -rf /var/lib/apt/lists/*
  - time sudo apt-get update -qq 2>&1
  
