language: ruby

sudo: required

matrix:
  include:
    - dist: precise
      env: dist=PRECISE
    - dist: trusty
      env: dist=TRUSTY

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    
install: true

script:
  - sudo apt-get install google-cloud-sdk
  
