language: rust
sudo: required
dist: trusty

services:
  - mysql
addons:
  postgresql: '9.4'

install: true
script:
  - mysql_config --libs
  - mysql_config --variable=pkglibdir
  - pkg-config --libs mysqlclient
