language: rust
sudo: required
dist: trusty

services:
  - mysql
addons:
  postgresql: '9.4'

install: true
script:
  - mysql_config --libs
  - pkg-config --libs mysqlclient
  - sudo find / -name "mysqlclient*"
  - cd `mysql_config --variable=pkglibdir`
  - sudo find . -name "mysqlclient*"
