#trigger
language: java

matrix:
  include:
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty

install:
  - sudo apt-get install python-libpcap python-dumbnet libwireshark-data
script: true
