language: ruby

sudo: required
dist: trusty

install: true
script:
  - cat /proc/net/dev
  - grep "eth0:\|wlan0" /proc/net/dev
  - export FOUND=`grep "eth0:\|wlan0" /proc/net/dev`
  - |
      if  [ -n "$FOUND" ] ; then
        echo yes
      else
        echo no
      fi
