language: ruby

install: true
script: cat ~/build.sh

env:
  global:
    - PACKAGECLOUD_TOKEN="test"

deploy:
  provider: script
  on:
    condition: "-n ${PACKAGECLOUD_TOKEN} && $CC == gcc"
  script: ./noscript.sh
