language: php

sudo: required
dist: precise

matrix:
  include:
    - php: hhvm
      group: stable
      env: GROUP=stable
    - php: hhvm
      group: deprecated-2017Q1
      env: GROUP=deprecated-2017Q1
    
install: true
script: true

