sudo: false

matrix:
  include:
    # General checks
    - os: linux
      go: &go_version 1.7.1
      env: TARGETS="check"

    # Filebeat
    - os: linux
      go: *go_version
      env: TARGETS="-C filebeat testsuite"
      
install: true
script: true
