sudo: required
dist: trusty

install: true
script:
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - deb https://apt.dockerproject.org/repo ubuntu-precise main
  - sudo apt-get install docker-engine
