language: ruby

services:
  - mongodb

matrix:
  include:
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty
    - sudo: required
      dist: trusty
      group: edge
    - sudo: required
      dist: trusty
      group: edge

script:
  - ruby mongoid_simple_example.rb
  - bundle exec ruby mongoid_simple_example.rb
