language: ruby

matrix:
  include:
    - sudo: false
      dist: precise
      env: SUDO=false DIST=precise
    - sudo: false
      dist: trusty
      env: SUDO=false DIST=trusty
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty

install: true
script: true

extras:
  build_tags: v1.0
  associated_hw: FH327B
  vibration_tested: False
