language: php

php: 7.0

matrix:
  include:
    - sudo: false
    - sudo: false
      dist: trusty
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

install: true
script:
  - php -i | grep "ICU version"
