language: ruby

matrix:
  include:
    - sudo: false
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

install: true
script:
  - echo "$CASHER_DIR/bin"
  - pushd $CASHER_DIR/bin
  - popd
  - eval curl https://raw.githubusercontent.com/travis-ci/casher/production/bin/casher -L -o $CASHER_DIR/bin/casher -s --fail
  - curl https://raw.githubusercontent.com/travis-ci/casher/production/bin/casher
