language: java

matrix:
  include:
    - sudo: false
    - sudo: required
      dist: precise
    - sudo: required
      dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

install: true
script: true
