language: elixir

sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install chromium
  - sudo apt-get install chromium-chromedriver
script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chromedriver &
