language: c

matrix:
  include:
    - sudo: required
      dist: precise
      env: SUDO=required DIST=precise
    - sudo: required
      dist: trusty
      env: SUDO=required DIST=trusty
      
install: true
script:
  - sudo apt-get install oracle-java9-installer
