language: ruby

install: true

script: true

before_deploy:
  - echo "before_deploy!"

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "test"
  - provider: s3
    skip_cleanup: true
