sudo: required
dist: trusty

language: c

install:
  - which python3
  - python3 -V
  - sudo ln -svf $(which python3) /usr/bin/python3
  - which python3
  - python3 -V
  - sudo python3 -m pip install pytest meson
script: true
